# Generated by Django 4.2.3 on 2023-07-19 15:54

import django.core.validators
from django.db import migrations, models
import settle.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[settle.common.validators.only_letters, django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=50)),
                ('location', models.TextField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
